-- =========================================
-- 00_drop_objects.sql
-- Apex Motorsport Database
-- =========================================

DROP TABLE QUALIFYING_LAP CASCADE CONSTRAINTS;
DROP TABLE RACE_RESULT CASCADE CONSTRAINTS;
DROP TABLE FUEL_CONSUMPTION CASCADE CONSTRAINTS;
DROP TABLE TELEMETRY_LOG CASCADE CONSTRAINTS;
DROP TABLE WEATHER_CONDITION CASCADE CONSTRAINTS;
DROP TABLE PITCREW_ASSIGNMENT CASCADE CONSTRAINTS;
DROP TABLE PITSTOP CASCADE CONSTRAINTS;
DROP TABLE DRIVER_SESSION CASCADE CONSTRAINTS;
DROP TABLE RACE_SESSION CASCADE CONSTRAINTS;
DROP TABLE EMP_EVENT_ASSIGNMENT CASCADE CONSTRAINTS;
DROP TABLE TIRE_SET CASCADE CONSTRAINTS;
DROP TABLE PITCREW_MEMBER CASCADE CONSTRAINTS;
DROP TABLE MECHANIC CASCADE CONSTRAINTS;
DROP TABLE ENGINEER CASCADE CONSTRAINTS;
DROP TABLE DRIVER CASCADE CONSTRAINTS;
DROP TABLE GEARBOX CASCADE CONSTRAINTS;
DROP TABLE POWER_UNIT CASCADE CONSTRAINTS;
DROP TABLE CHASSIS CASCADE CONSTRAINTS;
DROP TABLE AERO_COMPONENT CASCADE CONSTRAINTS;
DROP TABLE CAR_PART CASCADE CONSTRAINTS;
DROP TABLE PART CASCADE CONSTRAINTS;
DROP TABLE CAR CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE SHIPPED_ASSET CASCADE CONSTRAINTS;
DROP TABLE ASSET CASCADE CONSTRAINTS;
DROP TABLE SHIPMENT CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE SPONSOR_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE EMP_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE SEASON CASCADE CONSTRAINTS;
DROP TABLE CIRCUIT CASCADE CONSTRAINTS;
DROP TABLE CONTRACT CASCADE CONSTRAINTS;
DROP TABLE SPONSOR CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;

-- Optional cleanup for views
DROP VIEW VW_SHIPMENT_DETAILS;

-- Optional cleanup for indexes
DROP INDEX IDX_EMPLOYEE_DEPARTMENT;
DROP INDEX IDX_SHIPMENT_CIRCUIT;
DROP INDEX IDX_PAYMENT_CONTRACT;
