--INTELLIGENT KEYS??? (EMP001)
--Subtype entities to be added(ENGINEER, DRIVER, MECHANIC, PITCREW_MEMBER)??

CREATE TABLE DEPARTMENT (
    Department_Code VARCHAR2(10) PRIMARY KEY,
    Department_Description VARCHAR2(100) NOT NULL
);

CREATE TABLE EMPLOYEE (
    Emp_ID NUMBER PRIMARY KEY,
    Department_Code VARCHAR2(10) NOT NULL,
    Emp_FName VARCHAR2(50) NOT NULL,
    Emp_LName VARCHAR2(50) NOT NULL,
    Emp_DOB DATE,
    Emp_Contact VARCHAR2(20),
    Emp_Email VARCHAR2(100),
    Emp_Gender CHAR(1),
    Emp_Type VARCHAR2(30),

    CONSTRAINT FK_EMPLOYEE_DEPARTMENT
    FOREIGN KEY (Department_Code)
    REFERENCES DEPARTMENT(Department_Code)
);

CREATE TABLE SPONSOR (
    Sponsor_ID NUMBER PRIMARY KEY,
    Sponsor_Alias VARCHAR2(100) NOT NULL
);

CREATE TABLE CONTRACT (
    Contract_ID NUMBER PRIMARY KEY,
    Contract_Period VARCHAR2(50),
    Contract_Desc VARCHAR2(200),
    DateOfAgreement DATE
);

CREATE TABLE EMP_CONTRACT(
  Contract_ID NUMBER NOT NULL,
  Emp_ID NUMBER NOT NULL,

  CONSTRAINT PK_EMP_CONTRACT PRIMARY KEY(Contract_ID, Emp_ID),

  CONSTRAINT FK_EMP_CONTRACT1 FOREIGN KEY(Contract_ID) REFERENCES CONTRACT(Contract_ID),
  CONSTRAINT FK_EMP_CONTRACT2 FOREIGN KEY(Emp_ID) REFERENCES EMPLOYEE(Emp_ID)
);

CREATE TABLE SPONSOR_CONTRACT(
  Contract_ID NUMBER NOT NULL,
  Sponsor_ID NUMBER NOT NULL,

  CONSTRAINT PK_SPONSOR_CONTRACT PRIMARY KEY(Contract_ID, Sponsor_ID),

  CONSTRAINT FK_SPONSOR_CONTRACT1 FOREIGN KEY(Contract_ID) REFERENCES CONTRACT(Contract_ID),
  CONSTRAINT FK_SPONSOR_CONTRACT2 FOREIGN KEY(Sponsor_ID) REFERENCES SPONSOR(Sponsor_ID)
);

CREATE TABLE CIRCUIT (
    Circuit_ID NUMBER PRIMARY KEY,
    Circuit_Location VARCHAR2(100) NOT NULL,
    Circuit_TimeZone VARCHAR2(50)
);

CREATE TABLE SEASON (
    Season_ID NUMBER PRIMARY KEY,
    Season NUMBER(4) NOT NULL
);

CREATE TABLE PAYMENT (
    Payment_ID NUMBER PRIMARY KEY,
    Contract_ID NUMBER NOT NULL,
    Payment_Amount NUMBER(10,2),
    Transaction_Date DATE NOT NULL,

    CONSTRAINT FK_Contract_Payment
    FOREIGN KEY (Contract_ID)
    REFERENCES CONTRACT(Contract_ID)
);

CREATE TABLE SHIPMENT(
  Shipment_ID NUMBER PRIMARY KEY,
  Emp_ID NUMBER NOT NULL,
  Circuit_ID NUMBER NOT NULL,
  Departure_Date DATE,
  Arrival_Date DATE,
  Status NUMBER(1) CHECK(Status IN(1,2,3)), -- 1: NOT SHIPPED YET/2: IN TRANSIT/3: RECEIVED

  CONSTRAINT FK_Emp_Shipment FOREIGN KEY (Emp_ID) REFERENCES EMPLOYEE(Emp_ID),
  CONSTRAINT FK_Shipment_Circuit FOREIGN KEY(Circuit_ID) REFERENCES CIRCUIT(Circuit_ID)
);

CREATE TABLE ASSET(
  Asset_ID NUMBER PRIMARY KEY,
  Asset_Description VARCHAR2(100) NOT NULL,
  Asset_Quantity NUMBER CHECK (Asset_Quantity > 0)
);

CREATE TABLE SHIPPED_ASSET(
    Shipment_ID NUMBER NOT NULL,
    Asset_ID NUMBER NOT NULL,

    CONSTRAINT PK_SHIPPED_ASSET
    PRIMARY KEY (Shipment_ID, Asset_ID),

    CONSTRAINT FK_SHIPMENT_ASSET1
    FOREIGN KEY (Shipment_ID)
    REFERENCES SHIPMENT(Shipment_ID),

    CONSTRAINT FK_SHIPMENT_ASSET2
    FOREIGN KEY (Asset_ID)
    REFERENCES ASSET(Asset_ID)
);
