CREATE INDEX IDX_EMPLOYEE_DEPARTMENT
ON EMPLOYEE(Department_Code);

CREATE INDEX IDX_SHIPMENT_CIRCUIT
ON SHIPMENT(Circuit_ID);

CREATE INDEX IDX_PAYMENT_CONTRACT
ON PAYMENT(Contract_ID);

CREATE INDEX IDX_EVENT_CIRCUIT
ON EVENT(Circuit_ID);

CREATE INDEX IDX_EVENT_SEASON
ON EVENT(Season_ID);

CREATE INDEX IDX_EVENT_DATE
ON EVENT(Event_Date);

CREATE INDEX IDX_EEA_EMP
ON EMP_EVENT_ASSIGNMENT(Emp_ID);

CREATE INDEX IDX_EEA_EVENT
ON EMP_EVENT_ASSIGNMENT(Event_ID);

CREATE INDEX IDX_CAR_STATUS
ON CAR(Car_Status);

CREATE INDEX IDX_PART_TYPE
ON PART(Part_Type);