CREATE OR REPLACE TRIGGER TRG_CHECK_FUEL
BEFORE INSERT OR UPDATE
ON FUEL_CONSUMPTION
FOR EACH ROW
BEGIN
    IF :NEW.Fuel_Remaining < 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Fuel remaining cannot be negative.'
        );
    END IF;
END;
/
--INSERT INTO FUEL_CONSUMPTION VALUES (999,1,1,100,2,SYSTIMESTAMP,1,-5); Tester/
